"""empty message

Revision ID: 06a0e3b55a45
Revises: 941eb72647f5
Create Date: 2021-04-24 22:55:37.609820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a0e3b55a45'
down_revision = '941eb72647f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird_capture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en', sa.String(length=50), nullable=False),
    sa.Column('cnt', sa.String(length=50), nullable=False),
    sa.Column('loc', sa.String(length=200), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('rmk', sa.String(length=300), nullable=False),
    sa.Column('privacy', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnt'),
    sa.UniqueConstraint('en'),
    sa.UniqueConstraint('loc'),
    sa.UniqueConstraint('privacy'),
    sa.UniqueConstraint('rmk'),
    sa.UniqueConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bird_capture')
    # ### end Alembic commands ###
