"""empty message

Revision ID: 2b28e1ca3d40
Revises: 06a0e3b55a45
Create Date: 2021-04-24 23:34:45.921227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b28e1ca3d40'
down_revision = '06a0e3b55a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bird_capture_cnt_key', 'bird_capture', type_='unique')
    op.drop_constraint('bird_capture_en_key', 'bird_capture', type_='unique')
    op.drop_constraint('bird_capture_loc_key', 'bird_capture', type_='unique')
    op.drop_constraint('bird_capture_privacy_key', 'bird_capture', type_='unique')
    op.drop_constraint('bird_capture_rmk_key', 'bird_capture', type_='unique')
    op.drop_constraint('bird_capture_time_key', 'bird_capture', type_='unique')
    op.drop_constraint('user_first_name_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_first_name_key', 'user', ['first_name'])
    op.create_unique_constraint('bird_capture_time_key', 'bird_capture', ['time'])
    op.create_unique_constraint('bird_capture_rmk_key', 'bird_capture', ['rmk'])
    op.create_unique_constraint('bird_capture_privacy_key', 'bird_capture', ['privacy'])
    op.create_unique_constraint('bird_capture_loc_key', 'bird_capture', ['loc'])
    op.create_unique_constraint('bird_capture_en_key', 'bird_capture', ['en'])
    op.create_unique_constraint('bird_capture_cnt_key', 'bird_capture', ['cnt'])
    # ### end Alembic commands ###
